from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fpMainWindow(object):
    def setup_fp(self, fpMainWindow):
        fpMainWindow.setObjectName("fpMainWindow")
        fpMainWindow.resize(681, 391)
        fpMainWindow.setMinimumSize(QtCore.QSize(681, 391))
        fpMainWindow.setMaximumSize(QtCore.QSize(681, 391))
        fpMainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fpCentralWidget = QtWidgets.QWidget(fpMainWindow)
        self.fpCentralWidget.setObjectName("fpCentralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.fpCentralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.fpOuterFrame = QtWidgets.QFrame(self.fpCentralWidget)
        self.fpOuterFrame.setMinimumSize(QtCore.QSize(0, 371))
        self.fpOuterFrame.setMaximumSize(QtCore.QSize(661, 371))
        self.fpOuterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fpOuterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fpOuterFrame.setObjectName("fpOuterFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.fpOuterFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.fpInnerFrame = QtWidgets.QFrame(self.fpOuterFrame)
        self.fpInnerFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.fpInnerFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fpInnerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fpInnerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fpInnerFrame.setObjectName("fpInnerFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fpInnerFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fpVerticalLayout2 = QtWidgets.QVBoxLayout()
        self.fpVerticalLayout2.setObjectName("fpVerticalLayout2")
        self.fpHorizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.fpHorizontalLayout_7.setObjectName("fpHorizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.fpHorizontalLayout_7.addItem(spacerItem)
        self.fpEnterOtpLabel = QtWidgets.QLabel(self.fpInnerFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fpEnterOtpLabel.setFont(font)
        self.fpEnterOtpLabel.setObjectName("fpEnterOtpLabel")
        self.fpHorizontalLayout_7.addWidget(self.fpEnterOtpLabel)
        self.fpOtpLineEdit = QtWidgets.QLineEdit(self.fpInnerFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fpOtpLineEdit.setFont(font)
        self.fpOtpLineEdit.setObjectName("fpOtpLineEdit")
        self.fpHorizontalLayout_7.addWidget(self.fpOtpLineEdit)
        self.fpArrowLabel = QtWidgets.QLabel(self.fpInnerFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fpArrowLabel.setFont(font)
        self.fpArrowLabel.setText("")
        self.fpArrowLabel.setPixmap(QtGui.QPixmap("../../images/enter2_arrow.png"))
        self.fpArrowLabel.setObjectName("fpArrowLabel")
        self.fpHorizontalLayout_7.addWidget(self.fpArrowLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.fpHorizontalLayout_7.addItem(spacerItem1)
        self.fpVerticalLayout2.addLayout(self.fpHorizontalLayout_7)
        self.fpLine = QtWidgets.QFrame(self.fpInnerFrame)
        self.fpLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.fpLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.fpLine.setObjectName("fpLine")
        self.fpVerticalLayout2.addWidget(self.fpLine)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.fpVerticalLayout2.addItem(spacerItem2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.fpNpLabel = QtWidgets.QLabel(self.fpInnerFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fpNpLabel.setFont(font)
        self.fpNpLabel.setObjectName("fpNpLabel")
        self.horizontalLayout_6.addWidget(self.fpNpLabel)
        spacerItem4 = QtWidgets.QSpacerItem(33, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.fpNpLineEdit = QtWidgets.QLineEdit(self.fpInnerFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fpNpLineEdit.setFont(font)
        self.fpNpLineEdit.setObjectName("fpNpLineEdit")
        self.horizontalLayout_6.addWidget(self.fpNpLineEdit)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.fpVerticalLayout2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.fpCpLabel = QtWidgets.QLabel(self.fpInnerFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fpCpLabel.setFont(font)
        self.fpCpLabel.setObjectName("fpCpLabel")
        self.horizontalLayout_5.addWidget(self.fpCpLabel)
        spacerItem7 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.fpCpLineEdit = QtWidgets.QLineEdit(self.fpInnerFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fpCpLineEdit.setFont(font)
        self.fpCpLineEdit.setText("")
        self.fpCpLineEdit.setObjectName("fpCpLineEdit")
        self.horizontalLayout_5.addWidget(self.fpCpLineEdit)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.fpVerticalLayout2.addLayout(self.horizontalLayout_5)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.fpVerticalLayout2.addItem(spacerItem9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem10 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.fpSaveButton = QtWidgets.QPushButton(self.fpInnerFrame)
        self.fpSaveButton.setMinimumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fpSaveButton.setFont(font)
        self.fpSaveButton.setStyleSheet("border-radius: 4px;\n"
                                        "background-color: rgb(135, 229, 255);\n"
                                        "color: rgb(0, 0, 0);\n"
                                        "")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../images/save.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fpSaveButton.setIcon(icon)
        self.fpSaveButton.setObjectName("fpSaveButton")
        self.horizontalLayout_4.addWidget(self.fpSaveButton)
        spacerItem11 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.fpVerticalLayout2.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addLayout(self.fpVerticalLayout2, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.fpInnerFrame, 1, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem12, 2, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem13, 1, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem14, 1, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem15, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.fpOuterFrame, 0, 0, 1, 1)
        fpMainWindow.setCentralWidget(self.fpCentralWidget)

        self.retranslateUi(fpMainWindow)
        QtCore.QMetaObject.connectSlotsByName(fpMainWindow)

    def retranslateUi(self, fpMainWindow):
        _translate = QtCore.QCoreApplication.translate
        fpMainWindow.setWindowTitle(_translate("fpMainWindow", "Reset Password"))
        self.fpEnterOtpLabel.setText(_translate("fpMainWindow", "Enter OTP: "))
        self.fpOtpLineEdit.setToolTip(_translate("fpMainWindow", "Enter OTP sent to your email"))
        self.fpNpLabel.setText(_translate("fpMainWindow", "New Password: "))
        self.fpNpLineEdit.setToolTip(_translate("fpMainWindow", "Set new password"))
        self.fpCpLabel.setText(_translate("fpMainWindow", "Confirm Password: "))
        self.fpCpLineEdit.setToolTip(_translate("fpMainWindow", "Confirm password"))
        self.fpSaveButton.setText(_translate("fpMainWindow", "Save"))

